CREATE TABLE goose_db_version (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone NOT NULL DEFAULT now()
);
